<?php require 'contactForm.php'; //This handles sending the contact form ?>
<!DOCTYPE html>
<html lang="en">
  <head>
<!-- MUST BE IN EVERY HTML DOCUMENT. HEADER INFORMATION. -->
    <meta charset="UTF-8" />
    <meta name="description" content="Zetvue's personal website." />
    <meta name="theme-color" content="#E5383B" />
    <meta property="og:type" content="website" />
    <link rel="stylesheet" type="text/css" href="styles.css" />
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <meta name="viewport" content="width=device-width initial-scale=0.6" />
<!-- MUST BE IN EVERY HTML DOCUMENT. HEADER INFORMATION. -->
    <title>Zetvue - Main</title>
  </head>

  <body>

<!-- MUST BE IN EVERY HTML DOCUMENT. NAVBAR. -->
    <nav id="nav">
      <div class="navzetvue">
        <img
          src="assets/zetvuelogo.svg"
          height="40px"
          width="auto"
          alt="Zetvue Logo"
        />
      </div>

      <ul class="navlinks">
        <li class="navCurrentlyOn">
          <a href="/"> Home </a>
        </li>

        <li><a href="/portfolio.html"> Portfolio </a></li>
      </ul>
    </nav>
<!-- MUST BE IN EVERY HTML DOCUMENT. NAVBAR. -->

    <section class="introduction">
      <h1>Heya! I'm Zetvue.</h1>

      <p class="introMe">
        I'm a musician, designer, and very novice web developer.
      </p>

      <h1 class="introMedia">Media</h1>

      <h2>SOCIAL</h2>

      <ul class="introSVG">
        <a
          href="https://discord.id/?prefill=290131524957896705"
          target="_blank"
          rel="noreferrer noopener"
          ><img
            src="assets/discord.svg"
            height="30px"
            width="auto"
            alt="Discord"
        /></a>

        <a
          href="https://twitter.com/zetvue"
          target="_blank"
          rel="noreferrer noopener"
          ><img
            src="assets/twitter.svg"
            height="30px"
            width="auto"
            alt="Twitter"
        /></a>

        <a
          href="https://reddit.com/u/zetvue"
          target="_blank"
          rel="noreferrer noopener"
          ><img 
            src="assets/reddit.svg" 
            height="30px" 
            width="auto" 
            alt="Reddit"
        /></a>
      </ul>

        <h2>MUSIC</h2>

      <ul class="introSVG">
        <a
          href="https://open.spotify.com/artist/7o8JZ8DuQ9uCEpq5xM8C8K"
          target="_blank"
          rel="noreferrer noopener"
          ><img
            src="assets/spotify.svg"
            height="30px"
            width="auto"
            alt="Spotify"
        /></a>

        <a
          href="https://youtube.com/c/Zetvue"
          target="_blank"
          rel="noreferrer noopener"
          ><img
            src="assets/youtube.svg"
            height="30px"
            width="auto"
            alt="YouTube"
        /></a>

        <a
          href="https://soundcloud.com/zetvue"
          target="_blank"
          rel="noreferrer noopener"
          ><img
            src="assets/soundcloud.svg"
            height="30px"
            width="auto"
            alt="Soundcloud"
        /></a>

        <a
          href="https://zetvue.bandcamp.com"
          target="_blank"
          rel="noreferrer noopener"
        >
          <img
            src="assets/bandcamp.svg"
            height="20px"
            width="auto"
            alt="Bandcamp"
        /></a>
      </ul>

        <h2>PROGRAMMING</h2>

      <ul class="introSVG">
        <a
          href="https://github.com/zetvue"
          target="_blank"
          rel="noreferrer noopener"
          ><img src="assets/github.svg" height="30px" width="auto" alt="Github"
        /></a>

        <a
          href="https://gitlab.com/zetvue"
          target="_blank"
          rel="noreferrer noopener"
          ><img src="assets/gitlab.svg" height="30px" width="auto" alt="Gitlab"
        /></a>
      </ul>

        <h2>OTHER</h2>

      <ul class="introSVG">
        <a
          href="https://steamcommunity.com/id/zetvue"
          target="_blank"
          rel="noreferrer noopener"
          ><img src="assets/steam.svg" height="30px" width="auto" alt="Steam"
        /></a>
      </ul>

        <h2>CONTACT</h2>

      <div class="introSVG">
        <img
          src="assets/mail.svg"
          alt="Mail"
          height="25px"
          width="auto"
        />
      </div>
      <h6>
        The text above is an image to protect against bots and spammers.
      </h6>
      <form method="post">
        <label for="sender">Your e-mail</label><br>
        <input id="sender" name="sender" type="email" value="<?= $sender ?>" required /><br>

        <label for="message">Your message</label><br>
        <textarea id="message" name="message" required ><?= $message ?></textarea><br>

        <label for="antispam">What color is grass?</label><br>
        <input id="antispam" name="antispam" type="text" maxlength=5 value="<?= $antispam ?>" required /><br>

        <input type="submit" value="📨 Send"><br>
        <div id="contactFormResponse"><?= @$contactFormResponse ?></div>
      </form>
    </section>
  </body>
</html>
